### PR TITLE
Rebuild for Numpy 2.0

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
On windows - `numpy=2.0` with `mkl` fails:
```
    mkl:                     2024.1.0-h66d3029_692          conda-forge
    numpy:                   2.0.0-py312h49bc9c5_0          conda-forge
```
with the following error message: 
```
=========================== short test summary info ===========================
FAILED test/harmonic/test_dynamical_matrix.py::test_dynmat[True-C] - AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-05

Mismatched elements: 12 / 36 (33.3%)
Max absolute difference among violations: 0.08526585
Max relative difference among violations: 2.48573984
 ACTUAL: array([[ 3.591721e-17-0.j, -3.579184e-39+0.j, -4.090496e-39+0.j,
        -3.164400e-02+0.j, -5.833211e-18+0.j, -9.722018e-19+0.j],
       [-3.579184e-39-0.j, -8.451108e-18-0.j, -9.373090e-20+0.j,...
 DESIRED: array([[ 0.052897+0.j,  0.      +0.j,  0.      +0.j, -0.042597+0.j,
         0.      +0.j,  0.      +0.j],
       [ 0.      +0.j,  0.052897+0.j,  0.      +0.j,  0.      +0.j,...
FAILED test/harmonic/test_dynamical_matrix.py::test_dynmat[False-C] - AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-05

Mismatched elements: 12 / 36 (33.3%)
Max absolute difference among violations: 0.08526585
Max relative difference among violations: 2.48573984
 ACTUAL: array([[-2.716428e-18-0.j, -3.579184e-39+0.j, -4.090496e-39+0.j,
        -3.164400e-02+0.j, -5.833211e-18+0.j, -9.722018e-19+0.j],
       [-3.579184e-39-0.j, -3.138983e-17-0.j, -2.045248e-37+0.j,...
 DESIRED: array([[ 0.052897+0.j,  0.      +0.j,  0.      +0.j, -0.042597+0.j,
         0.      +0.j,  0.      +0.j],
       [ 0.      +0.j,  0.052897+0.j,  0.      +0.j,  0.      +0.j,...
================== 2 failed, 2 passed, 24 warnings in 2.17s ===================
```
I thought this was caused by a mix of `mkl` and `openblas` on windows but already `mkl` alone causes these issues.

**Comment by jan-janssen** [comment]
@conda-forge/core The `phonopy` package fails on numerical tests with `numpy=2.0` on windows. This seems to be related to `mkl`. Have you seen anything similar on other packages? Is this known? Are there specific BLAS commands which are affected?

**Comment by atztogo** [comment]
I leave my long comment below. In short, I think MKL is not the reason. I doubt the python-C binding code in phonopy, but I think I write it correctly. So I have no solution about it right now. Skipping win&numpy2.0 is our reasonable choice.

---

I have an experience that I obtained wrong eigenvector by `np.linalg.eigh` (Hermitian matrix) by a specific version of openblas conda package for macos-arm64. Because of this experience, I doubted blas, but this PR shows MKL seems OK because the blas of MKL is used for the numpy1.22 build, too, but for numpy1.22, the tests passed.

Computationally demanding part of phonopy is written in C. Until recently, I directly wrote the python-C binding I in a traditional way (direct C-API).  For the failure of win&numpy2.0, I doubted my code, so I rewrote the binding using nanobind that is the package to help writing the python-C binding. Unfortunately, even after using nanobind, the problem was not solved.

Now by carefully watching https://github.com/conda-forge/phonopy-feedstock/pull/151/checks (I leave the text copy of the test results at the bottom of this comment not to lose it), I noticed that I should still doubt the python-C binding.

(Almost to me not to forget) The reason is the test, `test/harmonic/test_force_constants.py::test_fc_cutoff_radius_svecs`. If I only use `dtype="intc"` (`int` in C) for passing numpy array to C code, the test passes, but with `dtype="int_"` (`long` in C), it failed. These two functions are different but similar. Something related to https://numpy.org/devdocs/numpy_2_0_migration_guide.html#windows-default-integer may be the reason...


```
test/api/test_api_phonopy.py::test_displacements_setter_NaCl PASSED      [  0%]
test/api/test_api_phonopy.py::test_forces_setter_NaCl_type1 PASSED       [  0%]
test/api/test_api_phonopy.py::test_forces_setter_NaCl_type2 PASSED       [  1%]
test/api/test_api_phonopy.py::test_energies_setter_NaCl_type1 PASSED     [  1%]
test/api/test_api_phonopy.py::test_energies_setter_NaCl_type2 PASSED     [  2%]
test/api/test_api_phonopy.py::test_mlp_NaCl_type2 SKIPPED (could not...) [  2%]
test/cui/test_phonopy_cui.py::test_phonopy_disp_Cr[False] PASSED         [  2%]
test/cui/test_phonopy_cui.py::test_phonopy_disp_Cr[True] PASSED          [  3%]
test/cui/test_phonopy_cui.py::test_phonopy_load PASSED                   [  3%]
test/cui/test_phonopy_cui.py::test_phonopy_is_check_symmetry PASSED      [  4%]
test/gruneisen/test_gruneisen.py::test_gruneisen_mesh FAILED             [  4%]
test/gruneisen/test_gruneisen.py::test_gruneisen_band FAILED             [  5%]
test/harmonic/test_derivative_dynmat.py::test_ddm_nac FAILED             [  5%]
test/harmonic/test_derivative_dynmat.py::test_ddm_nac_compact FAILED     [  5%]
test/harmonic/test_derivative_dynmat.py::test_ddm_nonac FAILED           [  6%]
test/harmonic/test_derivative_dynmat.py::test_ddm_nonac_compact FAILED   [  6%]
test/harmonic/test_displacements.py::test_nacl PASSED                    [  7%]
test/harmonic/test_displacements.py::test_si PASSED                      [  7%]
test/harmonic/test_displacements.py::test_sno2 PASSED                    [  7%]
test/harmonic/test_displacements.py::test_tio2 PASSED                    [  8%]
test/harmonic/test_displacements.py::test_tio2_random_disp[False-None] PASSED [  8%]
test/harmonic/test_displacements.py::test_tio2_random_disp[False-0.03] PASSED [  9%]
test/harmonic/test_displacements.py::test_tio2_random_disp[True-None] PASSED [  9%]
test/harmonic/test_displacements.py::test_tio2_random_disp[True-0.03] PASSED [ 10%]
test/harmonic/test_displacements.py::test_tio2_random_disp_with_random_dist[None] PASSED [ 10%]
test/harmonic/test_displacements.py::test_tio2_random_disp_with_random_dist[0.05] PASSED [ 10%]
test/harmonic/test_displacements.py::test_tio2_random_disp_with_random_dist[0.2] PASSED [ 11%]
test/harmonic/test_displacements.py::test_tio2_random_disp_with_random_dist_defualt[None] PASSED [ 11%]
test/harmonic/test_displacements.py::test_tio2_random_disp_with_random_dist_defualt[0.1] PASSED [ 12%]
test/harmonic/test_displacements.py::test_tio2_random_disp_with_random_max_distance PASSED [ 12%]
test/harmonic/test_displacements.py::test_tio2_random_disp_plusminus PASSED [ 12%]
test/harmonic/test_displacements.py::test_zr3n4 PASSED                   [ 13%]
test/harmonic/test_displacements.py::test_tipn3 PASSED                   [ 13%]
test/harmonic/test_dynamical_matrix.py::test_dynmat[True-C] FAILED       [ 14%]
test/harmonic/test_dynamical_matrix.py::test_dynmat[True-Py] PASSED      [ 15%]
test/harmonic/test_dynamical_matrix.py::test_dynmat[False-Py] PASSED     [ 15%]
test/harmonic/test_dynamical_matrix.py::test_dynmat_dense_svecs[C] ERROR [ 15%]
test/harmonic/test_dynamical_matrix.py::test_dynmat_dense_svecs[Py] ERROR [ 16%]
test/harmonic/test_dynamical_matrix.py::test_dynmat_gonze_lee FAILED     [ 16%]
test/harmonic/test_dynamical_matrix.py::test_dynmat_gonze_lee_short_range_fc FAILED [ 17%]
test/harmonic/test_dynamical_matrix.py::test_dynmat_gonze_lee_full_term FAILED [ 17%]
test/harmonic/test_dynamical_matrix.py::test_dynmat_wang FAILED          [ 17%]
test/harmonic/test_dynmat_to_fc.py::test_get_commensurate_points PASSED  [ 18%]
test/harmonic/test_dynmat_to_fc.py::test_get_commensurate_points_in_integers PASSED [ 18%]
test/harmonic/test_dynmat_to_fc.py::test_ph2ph_with_nac FAILED           [ 19%]
test/harmonic/test_dynmat_to_fc.py::test_ph2ph_without_nac FAILED        [ 19%]
test/harmonic/test_dynmat_to_fc.py::test_with_eigenvalues FAILED         [ 20%]
test/harmonic/test_dynmat_to_fc.py::test_with_dynamical_matrices[False-C] FAILED [ 20%]
test/harmonic/test_dynmat_to_fc.py::test_with_dynamical_matrices[True-C] FAILED [ 20%]
test/harmonic/test_dynmat_to_fc.py::test_with_dynamical_matrices[False-Py] FAILED [ 21%]
test/harmonic/test_dynmat_to_fc.py::test_with_dynamical_matrices[True-Py] FAILED [ 21%]
test/harmonic/test_force_constants.py::test_fc PASSED                    [ 22%]
test/harmonic/test_force_constants.py::test_fc_nofcsym PASSED            [ 22%]
test/harmonic/test_force_constants.py::test_fc_compact_fcsym PASSED      [ 23%]
test/harmonic/test_force_constants.py::test_fc_compact_symfc SKIPPED     [ 23%]
test/harmonic/test_force_constants.py::test_fc_cutoff_radius[False] PASSED [ 23%]
test/harmonic/test_force_constants.py::test_fc_cutoff_radius[True] PASSED [ 24%]
test/harmonic/test_force_constants.py::test_fc_cutoff_radius_svecs[False-False] PASSED [ 24%]
test/harmonic/test_force_constants.py::test_fc_cutoff_radius_svecs[False-True] FAILED [ 25%]
test/harmonic/test_force_constants.py::test_fc_cutoff_radius_svecs[True-False] PASSED [ 25%]
test/harmonic/test_force_constants.py::test_fc_cutoff_radius_svecs[True-True] FAILED [ 25%]
test/harmonic/test_force_constants.py::test_rearrange_force_constants_array FAILED [ 26%]
test/interface/test_CP2K.py::test_read_cp2k SKIPPED (not found cp2k-...) [ 26%]
test/interface/test_CRYSTAL.py::test_read_crystal PASSED                 [ 27%]
test/interface/test_TURBOMOLE.py::test_read_turbomole PASSED             [ 27%]
test/interface/test_abacus.py::test_read_abacus_nomag PASSED             [ 28%]
test/interface/test_abacus.py::test_read_abacus_mag PASSED               [ 28%]
test/interface/test_abacus.py::test_read_abacus_output PASSED            [ 28%]
test/interface/test_abinit.py::test_read_abinit PASSED                   [ 29%]
test/interface/test_castep.py::test_read_castep PASSED                   [ 29%]
test/interface/test_lammps.py::test_LammpsStructure[H] PASSED            [ 30%]
test/interface/test_lammps.py::test_LammpsStructure[Ti] PASSED           [ 30%]
test/interface/test_lammps.py::test_LammpsStructure_from_file[H] PASSED  [ 30%]
test/interface/test_lammps.py::test_LammpsStructure_from_file[Ti] PASSED [ 31%]
test/interface/test_lammps.py::test_LammpsStructureDumper PASSED         [ 31%]
test/interface/test_lammps.py::test_LammpsStructureDumper_Ti[H] PASSED   [ 32%]
test/interface/test_lammps.py::test_LammpsStructureDumper_Ti[Ti] PASSED  [ 32%]
test/interface/test_lammps.py::test_LammpsStructureDumper_Ti[Ti_id] PASSED [ 33%]
test/interface/test_lammps.py::test_LammpsForcesLoader PASSED            [ 33%]
test/interface/test_phonopy_yaml.py::test_read_poscar_yaml PASSED        [ 33%]
test/interface/test_phonopy_yaml.py::test_read_phonopy_yaml PASSED       [ 34%]
test/interface/test_phonopy_yaml.py::test_read_phonopy_yaml_with_stream PASSED [ 34%]
test/interface/test_phonopy_yaml.py::test_PhonopyYaml_read PASSED        [ 35%]
test/interface/test_phonopy_yaml.py::test_PhonopyYaml_read_with_stream PASSED [ 35%]
test/interface/test_phonopy_yaml.py::test_read_cell_yaml PASSED          [ 35%]
test/interface/test_phonopy_yaml.py::test_read_cell_yaml_with_stream PASSED [ 36%]
test/interface/test_phonopy_yaml.py::test_write_phonopy_yaml PASSED      [ 36%]
test/interface/test_phonopy_yaml.py::test_write_phonopy_yaml_extra PASSED [ 37%]
test/interface/test_phonopy_yaml.py::test_load_nac_yaml PASSED           [ 37%]
test/interface/test_pwmat.py::test_read_pwmat PASSED                     [ 38%]
test/interface/test_pwmat.py::test_magmom PASSED                         [ 38%]
test/interface/test_pwscf.py::test_read_pwscf PASSED                     [ 38%]
test/interface/test_pypolymlp.py::test_pypolymlp_develop SKIPPED (co...) [ 39%]
test/interface/test_vasp.py::test_read_vasp PASSED                       [ 39%]
test/interface/test_vasp.py::test_get_vasp_structure_lines[None-True] PASSED [ 40%]
test/interface/test_vasp.py::test_get_vasp_structure_lines[None-False] PASSED [ 40%]
test/interface/test_vasp.py::test_get_vasp_structure_lines[my_comment-True] PASSED [ 41%]
test/interface/test_vasp.py::test_get_vasp_structure_lines[my_comment-False] PASSED [ 41%]
test/interface/test_vasp.py::test_get_vasp_structure_lines_shuffled_positions PASSED [ 41%]
test/interface/test_vasp.py::test_parse_vasprun_xml PASSED               [ 42%]
test/interface/test_vasp.py::test_VasprunxmlExpat PASSED                 [ 42%]
test/interface/test_vasp.py::test_parse_set_of_forces PASSED             [ 43%]
test/interface/test_vasp.py::test_read_XDATCAR PASSED                    [ 43%]
test/interface/test_vasp.py::test_write_XDATCAR PASSED                   [ 43%]
test/interface/test_wien2k.py::test_parse_wien2k_struct PASSED           [ 44%]
test/phonon/test_band_structure.py::test_band_structure FAILED           [ 44%]
test/phonon/test_band_structure.py::test_band_structure_gv FAILED        [ 45%]
test/phonon/test_band_structure.py::test_band_structure_bc FAILED        [ 45%]
test/phonon/test_dos.py::testTotalDOS FAILED                             [ 46%]
test/phonon/test_dos.py::testTotalDOSTetrahedron FAILED                  [ 46%]
test/phonon/test_dos.py::testProjectedlDOS FAILED                        [ 46%]
test/phonon/test_dos.py::testPartialDOSTetrahedron FAILED                [ 47%]
test/phonon/test_dos.py::test_get_pdos_indices PASSED                    [ 47%]
test/phonon/test_group_velocity.py::test_gv_nacl FAILED                  [ 48%]
test/phonon/test_group_velocity.py::test_gv_si FAILED                    [ 48%]
test/phonon/test_irreps.py::test_pt03_P2 FAILED                          [ 48%]
test/phonon/test_irreps.py::test_pt04_Pc FAILED                          [ 49%]
test/phonon/test_irreps.py::test_pt06_P222_1 FAILED                      [ 49%]
test/phonon/test_irreps.py::test_pt07_Amm2 FAILED                        [ 50%]
test/phonon/test_irreps.py::test_pt09_P4_1 FAILED                        [ 50%]
test/phonon/test_irreps.py::test_pt10_Pbar4 FAILED                       [ 51%]
test/phonon/test_irreps.py::test_pt11_I4_1a FAILED                       [ 51%]
test/phonon/test_irreps.py::test_pt13_P4mm FAILED                        [ 51%]
test/phonon/test_irreps.py::test_pt14_Pbar42_1m FAILED                   [ 52%]
test/phonon/test_irreps.py::test_pt19_P3m1 FAILED                        [ 52%]
test/phonon/test_irreps.py::test_pt19_P31m FAILED                        [ 53%]
test/phonon/test_irreps.py::test_pt20_Pbar3m1 FAILED                     [ 53%]
test/phonon/test_irreps.py::test_pt21_P6 FAILED                          [ 53%]
test/phonon/test_irreps.py::test_pt22_Pbar6 FAILED                       [ 54%]
test/phonon/test_irreps.py::test_pt24_P6_222 FAILED                      [ 54%]
test/phonon/test_irreps.py::test_pt26_Pbar6m2 FAILED                     [ 55%]
test/phonon/test_irreps.py::test_pt28_P2_13 FAILED                       [ 55%]
test/phonon/test_irreps.py::test_pt29_Pabar3 FAILED                      [ 56%]
test/phonon/test_irreps.py::test_pt30_P4_332 FAILED                      [ 56%]
test/phonon/test_irreps.py::test_pt31_Pbar43m FAILED                     [ 56%]
test/phonon/test_mesh.py::test_Mesh_nofcsym FAILED                       [ 57%]
test/phonon/test_mesh.py::test_Mesh_full_fcsym FAILED                    [ 57%]
test/phonon/test_mesh.py::test_Mesh_compact_fcsym FAILED                 [ 58%]
test/phonon/test_mesh.py::test_Mesh_full_fcsym_nonac FAILED              [ 58%]
test/phonon/test_mesh.py::test_Mesh_full_fcsym_wang FAILED               [ 58%]
test/phonon/test_mesh.py::test_Mesh_full_fcsym_si FAILED                 [ 59%]
test/phonon/test_modulation.py::test_modulation FAILED                   [ 59%]
test/phonon/test_moment.py::test_moment FAILED                           [ 60%]
test/phonon/test_qpoints.py::testQpoints FAILED                          [ 60%]
test/phonon/test_random_displacements.py::test_random_displacements_Zr3N4 PASSED [ 61%]
test/phonon/test_random_displacements.py::test_random_displacements_all_atoms_TiPN3 FAILED [ 61%]
test/phonon/test_random_displacements.py::test_random_displacements_all_atoms_TiPN3_max_distance FAILED [ 61%]
test/phonon/test_random_displacements.py::test_tio2_random_disp_plusminus[True] PASSED [ 62%]
test/phonon/test_random_displacements.py::test_tio2_random_disp_plusminus[False] PASSED [ 62%]
test/phonon/test_random_displacements.py::test_treat_imaginary_modes FAILED [ 63%]
Windows fatal exception: int divide by zero
```

**Pull request closed without merging**
