### PR TITLE
Enable test after change in dir structure upstream

### PR DESCRIPTION
**Pull request by jochym**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jochym** [comment]
@conda-forge-admin, please rerender

**Comment by jochym** [comment]
@atztogo Let us fix the standard build here first - before extending this to pypy.

**Comment by jochym** [comment]
@atztogo (somewhat) good news: if I install current c-f linux package into new environment (locally) and run the tests on clean test directory from the phonopy/master  the tests run fine (except random disp).
So at least the public package is OK.

**Comment by jochym** [comment]
@atztogo I have "cheated" the process by removing problematic tests on linux. There is a number of them. I guess they are all connected with linking with wrong spglib version. Could you verify this hypothesis?

**Comment by atztogo** [comment]
Many tests on travis-CI for develop branch had failed. Probably the issue came from `dynamical_matrix.py`. I changed the code in 'develop' branch as found here, https://github.com/phonopy/phonopy/compare/f5c61c758fc7...8ce43ddb7128. `G_vec_list = np.dot(G, rec_lat.T)` was the source of the problem in my failure in travis-CI. I don't know why this can be the problem. But it may be memory size issue of docker (VM?).

At these commits, I also disconnected spglib from phonopy. Now spglib is imported from separately installed package. I can release this commit as v2.7.0. What is the best to do? Still the test random_displacements.py fails. This is a different issue.

**Comment by jochym** [comment]
We can run a separate PR sourced at github develop branch - to test if all is fine. You do not need to release it yet. I will switch it if all is fine. Is the develop branch ready for testing?

**Comment by jochym** [comment]
Release candidate PR: https://github.com/conda-forge/phonopy-feedstock/pull/73
We can work on 2.7.0rc there

**Pull request closed without merging**
